### ISSUE TITLE
Alias prefix issue (nonexistent alias suggestion)

### ISSUE THREAD

**Issue by mpolakovic** [djui/alias-tips#11]
Should you define `m` as an alias for `make`, for example, then running `makepkg` will prompt the plugin to remind you that there's an alias for that (`mpkg` in this case) even though there's no such alias.

**Comment by djui** [comment]
I can reproduce. It's a bit tricker to fix (not regress on other aliases) but should be possible.

**Comment by djui** [comment]
@mpolakovic Could you try again if this solves your problem?

**Comment by mpolakovic** [comment]
@djui I can confirm that a5b5e38 fixes this issue. Thank you!
