### ISSUE TITLE
Tips for git

### ISSUE THREAD

**Issue by pradyunsg** [djui/alias-tips#12]
How about adding tips support for git's own aliases?

Say, I have a `git alias c commit`.

So, if I run 
```sh
git commit -m "new commit"
```

It would be nice if I got a message for that like:
```
Alias Tip: git c -m "new commit"
```

**Comment by djui** [comment]
Great idea. Will try to make some time for it. Otherwise, of course, pull-requests are welcome!

**Comment by pradyunsg** [comment]
I actually started on this and then my laptop's display chip (or whatever the chip at the bottom of the screen is called) died. Now, I can't really do anything without a development machine.

------

Anyway, here's what I had figured out (the NOTES.md file, copy-paste):

## Git Aliases
- Getting the list of aliases valid in the current context.

  ```
  git config --get-regexp '^alias\.'
  ```

- It might be a nice idea to have tips about alternate commands, like telling them to use some nicer alias for log that is there instead of the basic log command. Or maybe not. Discuss.

- Can I assume git is installed? No.
  If it isn't installed, boo the user. For nicer UX. :wink: Discuss.

**Comment by djui** [comment]
Good ideas. I think I can just parse `git alias` to get a list of aliases.
