### ISSUE TITLE
Use nosetests and a data driven test approach

### ISSUE THREAD

**Issue by pradyunsg** [djui/alias-tips#13]
I was looking at the test code and there's a *lot* of repetition. Consider using some sort of data-driven testing. It'll make the tests easier to write and work with.

Suggestions:
 - You can reuse this decorator [marked here][py2c-test-decorator].
 - Read [this][blog-link] page for some ideas.

[py2c-test-decorator]: https://github.com/pradyunsg/Py2C/blob/f907f977c845a0bb09915ab3d12854666582e1e0/py2c/tests/__init__.py#L140-L191
[blog-link]: http://defragdev.com/blog/?p=660

**Comment by pradyunsg** [comment]
Whoops!

**Comment by pradyunsg** [comment]
Just edited the OP.

**Comment by djui** [comment]
Thanks for the idea. I would like to keep the verbose style and not switch to Table-driven (Data-driven) testing so I can create classes and let the test function name document test outputs and more granularity on which test case failed which should give me easier understanding when trying to fix it. 

Please let me know if you have ideas on how to combine test classes and test function names and table driven testing, then I can reopen the issue again.

**Comment by pradyunsg** [comment]
Well, in the first link, you can do so...

Check out https://github.com/pradyunsg/Py2C/blob/f907f977c845a0bb09915ab3d12854666582e1e0/py2c/tree/tests/data/node-assignment.yaml (and any other yaml file) in the same repo.

**Comment by pradyunsg** [comment]
Would you mind if I made a PR demonstrating this?

**Comment by djui** [comment]
Yes, please.

**Comment by pradyunsg** [comment]
I'll do so, after I fix the new testing-package I'm writing or once ddt accepts my PR or I decide to ditch them both and write something for this package.

Basically, latest by tomorrow.

**Comment by pradyunsg** [comment]
Ah. Tomorrow never came. I got carried away with `ddt` and ended up rewriting that package. I apologize for that.

I'm now taking on an issue over a pypa/pip. I won't be able to bother you with the PR just yet. Rest assured I will though.

I hope to I write the PR for this after I get my work into ddt upstream. Otherwise, nose-parameterized. :wink:

**Comment by djui** [comment]
Thanks for the heads up and update, and definitely no worries.
