### ISSUE TITLE
"git alias" is not a git command

### ISSUE THREAD

**Issue by ngg** [djui/alias-tips#15]
git: 'alias' is not a git command. See 'git --help'.

I think you have a git alias named "alias", but it is not working for me.
Pls use the real git command, I think it might be something like 'git config --get-regexp "^alias."'

**Comment by djui** [comment]
Thanks for reporting this. `git-alias` was a tool in https://github.com/tj/git-extras/blob/master/Commands.md#git-alias that I had installed without thinking about its origin.

**Comment by djui** [comment]
https://github.com/djui/alias-tips/commit/89b1d7c92f7adfbde33dc44e62ee7c1d6552aa07 fixes the issue. Sorry for the inconvenience.

**Comment by ngg** [comment]
Thanks for the fast fix!
