### ISSUE TITLE
Allow ignoring certain aliases.

### ISSUE THREAD

**Issue by tomprince** [djui/alias-tips#3]
It would be nice to be able to ignore certain aliases. For example, if I have an alias to correct a common-typo, I don't want to be reminded of the typo if I type the correct command.

**Comment by djui** [comment]
Sounds reasonable; only look up aliases one way, if bidirectional, I understand correctly?

How would you like to have the list being defined?

**Comment by tomprince** [comment]
> only look up aliases one way, if bidirectional, I understand correctly?

I'm not sure I understand what you are saying here.

I have, for example
```zsh
alias vi=nvim
alias vim=nvim
```
because I have muscle memory for those two commands. When I *do* type `nvim`, I don't want to be reminded that I sometimes don't.

> How would you like to have the list being defined?

I hadn't thought about that. I guess maybe a `zstyle` of some description?

**Comment by djui** [comment]
@tomprince Does this look useful enough? https://github.com/djui/alias-tips/pull/4

**Comment by tomprince** [comment]
That looks sufficient.
