### ISSUE TITLE
not only does force abort the command I'm running, it aborts my entire zsh session

### ISSUE THREAD

**Issue by graingert** [djui/alias-tips#37]
I don't feel like I deserve that much punishment!

**Comment by orestisf1993** [comment]
Ouch. I was starting a new zsh session and didn't notice that `exit` exits the whole shell. Sorry about that.

**Comment by djui** [comment]
Is any of your able to address this, seeing a viable solution? Otherwise I can revert the change.

**Comment by orestisf1993** [comment]
`if [[ $ret = $force_exit_code ]]; then kill -s INT $$ ; fi` seems to have the desired behavior. I don't know if this can cause any undesired side effects.

**Comment by pradyunsg** [comment]
@orestisf1993 Feel free to make a PR for this. :)
