### ISSUE TITLE
Python Required?

### ISSUE THREAD

**Issue by rdegges** [djui/alias-tips#52]
I'm currently cleaning up my dotfiles, and noticed some weird issues when using pyenv. I use pyenv exclusively for my development stuff, and try to keep my global userspace as clean as possible.

Because of this, I narrowed down the following error message to this plugin:

```
Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python' from deb python-is-python3
```

This basically appears on my CLI after each command I run, until I manually load pyenv (by running pyenv) to activate the shim, at which point this plugin starts working.

It would be super cool if this plugin could work without relying on a system python.

**Comment by djui** [comment]
Yeah, I know, or any other language that could compile to a binary, which would also make it faster. For now Python it is. I think someone else ported it to pure Shell, but can't find it anymore.
