### ISSUE TITLE
grep: (standard input): binary file matches

### ISSUE THREAD

**Issue by jeffreytse** [djui/alias-tips#56]
When the function has special characters, this plugin will show up this error information output by `grep`, this error was shown on every executed command, [here](https://github.com/djui/alias-tips/blob/23fd139300256230764ea17972ba98aca84cdeb7/alias-tips.plugin.zsh#L46) is the key code line caused the error, it could be easily reproduced by using [zsh-vi-mode](https://github.com/jeffreytse/zsh-vi-mode) at the same time.

![image](https://user-images.githubusercontent.com/9413601/117155834-b5928700-adef-11eb-96f3-210078f53dde.png)

![image](https://user-images.githubusercontent.com/9413601/117175265-3c039480-ae01-11eb-9a84-47cd35f7b2f2.png)

**Comment by jeffreytse** [comment]
Issue: jeffreytse/zsh-vi-mode#97

**Comment by djui** [comment]
Thanks @jeffreytse I can merge this right away, just want to understand what’s happening:

How is it possible that `egrep` sees piped data from `functions` as binary? Does the `zsh-vi-mode` overload `functions`? None of the functions declared in the plug-in seem have non-ascii characters.

min addition to your silencing patch, maybe it’s a good idea to enforce `egrep` to expect only non-binary content: `egrep -a`?

**Comment by jeffreytse** [comment]
Hi @djui I think the `functions` will output all the functions, but in case the implementation of some functions would has special characters, such as some control characters, it would cause the output looks like binary file for `egrep`.

**Comment by jeffreytse** [comment]
Hi @djui ,  zsh-vi-mode does nothing about the `functions` or `grep`, you could have a future test on the zsh-vi-mode plugin. I think we should redirect the error of grey to /dev/null when we use subshell to capture the std output.
