### ISSUE TITLE
preexec:1: no such file or directory: ./alias-tips

### ISSUE THREAD

**Issue by justmytwospence** [djui/alias-tips#6]
I get this error every time I run a command.

**Comment by djui** [comment]
Looks like either file does not exist or it calculates the wrong path to the file; likely ZSH_PLUGINS is not set.
Can you reply to the following questions:

- How did you install alias-tips
- Which shell are you using
- What zag helper are you using

**Comment by justmytwospence** [comment]
I got it working, not sure how to reproduce exactly. Closing.
